org: js2023
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${aws:region}:*:table/*

functions:
  getRooms:
    handler: getRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: get

  addRoom:
    handler: addRoom/index.handler
    events:
      - httpApi:
          path: /rooms
          method: post

resources:
  Resources:
    rooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: RoomType
            AttributeType: S
          - AttributeName: Quantity
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: RoomType
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: RoomTypeIndex
            KeySchema:
              - AttributeName: RoomType
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    bookings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: CustomerId
            AttributeType: S
          - AttributeName: checkin
            AttributeType: S
          - AttributeName: checkout
            AttributeType: S
          - AttributeName: Guests
            AttributeType: N
          - AttributeName: RoomType
            AttributeType: S
          - AttributeName: RoomQuantity
            AttributeType: N
          - AttributeName: TotalSum
            AttributeType: N
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: CheckinIndex
            KeySchema:
              - AttributeName: checkin
                KeyType: HASH
            Projection:
              ProjectionType: ALL
