# org: js2023
# org: js2023
service: bonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${aws:region}:*:table/*

functions:
  getRooms:
    handler: getRooms/index.handler
    events:
      - httpApi:
          path: /rooms/{type}
          method: get

  addRoom:
    handler: addRoom/index.handler
    events:
      - httpApi:
          path: /rooms
          method: post

  deleteBooking:
    handler: deleteBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: delete

  getBookings:
    handler: getBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

  getCustomer:
    handler: getCustomer/index.handler
    events:
      - httpApi:
          path: /bookings/{customerId}
          method: get
          
  newBooking:
    handler: newBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post

resources:
  Resources:
    rooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: id
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        # GlobalSecondaryIndexes:
        #   - IndexName: RoomTypeIndex
        #     KeySchema:
        #       - AttributeName: RoomType
        #         KeyType: "RANGE"
        #     Projection:
        #       ProjectionType: ALL

    bookings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings
        AttributeDefinitions:
          - AttributeName: bookingReference
            AttributeType: S
          - AttributeName: customer
            AttributeType: S
        KeySchema:
          - AttributeName: bookingReference
            KeyType: HASH
          - AttributeName: customer
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

        # GlobalSecondaryIndexes:
        #   - IndexName: 
        #     KeySchema:
        #       - AttributeName: 
        #         KeyType: "RANGE"
        #     Projection:
        #       ProjectionType: ALL